<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="cartbot">

    <xacro:include filename="$(find cartbot)/xacro/robot1/cartbot.gazebo.xacro" />
    <xacro:include filename="$(find cartbot)/xacro/robot1/lidar.xacro" />

    <xacro:property name="body_mass" value="15"/>
    <xacro:property name="body_width" value="0.4"/>
    <xacro:property name="body_height" value="0.25"/>
    <xacro:property name="body_length" value="0.6"/>
    <xacro:property name="wheel_gap" value="0.46"/>
    <xacro:property name="wheel_mass" value="2"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="ground_clearnace" value="0.15"/>

    <material name="blue">
        <color rgba="0.0 0.0 1.0 0.8"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <xacro:macro name="box_inertia" params="m w h d">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m / 12.0 * (d*d + h*h)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (w*w + h*h)}" iyz="0.0" izz="${m / 12.0 * (w*w + d*d)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}"/>
        </inertial>
    </xacro:macro>

    <link name='base_footprint'/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="body_link"/>
        <origin xyz="0.0 0.0 ${body_height/2 + ground_clearnace}" rpy="0 0 0"/>
    </joint>

    <link name='body_link'>
        <xacro:box_inertia m="${body_mass}" w="${body_width}" h="${body_height}" d="${body_length}"/>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
    </link>

    <link name='wheel_left_link'>
        <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
    </link>

    <joint name="wheel_left_joint" type="continuous">
        <parent link="body_link"/>
        <child link="wheel_left_link"/>
        <origin xyz="-${body_length/2 - wheel_radius} ${wheel_gap/2*1} -${ground_clearnace+body_height/2 - wheel_radius}" rpy="-${pi/2} 0.0 0.0"/>
        <axis xyz="0 0 1"/>
        <limit effort="10000" velocity="1000"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <link name='wheel_right_link'>
        <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
    </link>

    <joint name="wheel_right_joint" type="continuous">
        <parent link="body_link"/>
        <child link="wheel_right_link"/>
        <origin xyz="-${body_length/2 - wheel_radius} ${wheel_gap/2*-1} -${ground_clearnace+body_height/2 - wheel_radius}" rpy="${pi/2} 0.0 0.0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="10000" velocity="1000"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <joint name="caster_joint" type="fixed">
        <parent link="body_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="0.2 0.0 -${body_height/2 + ground_clearnace/2}" rpy="0.0 0.0 0.0" />
    </joint>

    <link name='caster_wheel_link'>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${ground_clearnace/2}" />
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${ground_clearnace/2}" />
            </geometry>
        </collision>
    </link>
</robot>
